[package]
name = "shople"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.3.0"
random = "0.14.0"
serde = "1.0.198"
serde_derive = "1.0.198"
